### PR TITLE
Clarify software license

### PR DESCRIPTION
**Pull request by kf6nux**
I'm guessing that including the link to https://opensource.bloom.sh/licensing in the README.md was not intended cause this software to be subject to the GNU Affero General Public License (AGPL) v3.0 & Server Side Public License (SSPL) v1.0.

This PR clarifies the licensing sections I suspect the author intended people to reference when arriving at that page.

### CODE REVIEW

**Comment by z0mbie42** [comment]
Hi, sorry if it's not clear, I'll update https://opensource.bloom.sh/licensing.

This library is licensed under Apache v2.0 only.

Commercial licenses are available for projects licensed under AGPLv3 or SSPLv1 and people do want to sell the projects commercially who rely on bloom's open source projects but do not want to open source their stack.

So apache2 projects are not related to the commercial licenses section and you can do ~almost whatever you want, according to the apache2 license.

**Comment by z0mbie42** [comment]
@kf6nux according to you, the best way to make it clear that this library is only licensed under Apachev2 is : 
* remove the link to https://opensource.bloom.sh/licensing in the `License` section in the README
* improve https://opensource.bloom.sh/licensing wording
?

**Comment by z0mbie42** [comment]
hi again,
Sorry if I felt abrupt by closing the PR immediately.

Do you see actionable steps to solve to undergoing issue (licensing not clear enough) ?

**Comment by kf6nux** [comment]
Thanks for the bump @z0mbie42 

I agree either of your bullets would work.

I'd recommend your first suggestion of removing the link from the Licensing section of the readme if there's no intention for the link to further clarify the license.

My personal preference is for all licensing information to be check into version control.

**Pull request closed without merging**
